name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1

    - name: Build and push Docker image
      run: |
        cd backend
        docker build -t product-manager .
        docker tag product-manager:latest <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/product-manager:latest
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/product-manager:latest

    - name: Deploy to EC2
      run: |
        ssh -i ~/ssh/product-manager-backend.pem ubuntu@35.171.17.9 "docker pull <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/product-manager:latest && docker run -d -p 80:3000 <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/product-manager:latest"
