name: Deploy to AWS

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9u6w8s4

    - name: Build and push Docker image
      run: |
        cd backend
        docker build -t public.ecr.aws/q9u6w8s4/product-manager:latest .
        docker push public.ecr.aws/q9u6w8s4/product-manager:latest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa


    # - name: Deploy to EC2
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@35.171.17.9 "docker pull public.ecr.aws/q9u6w8s4/product-manager:latest && docker run -d -p 80:3000 public.ecr.aws/q9u6w8s4/product-manager:latest"
